Repository eosphoros-ai/DB-GPT-Web, pull requests merged in 2023-09, with the labels that each got.

#24 V230817 i18n
  app/datastores/documents/chunklist/page.tsx
  app/datastores/documents/page.tsx
  app/datastores/page.tsx
  app/i18n.js
  app/layout.tsx
  app/page.tsx
  components/SpaceParameter.tsx
  components/leftSide.tsx
  package-lock.json
  package.json
Labels: enhancement

#27 remove unused dependencies and devDependencies
  .gitignore
  app/page.tsx
  components/MonacoEditor.tsx
  components/chatBoxTemp.tsx
  components/dbEditor.tsx
  components/reactMonacoEditor.tsx
  hooks/useVisitorId.ts
  main.py
  package-lock.json
  package.json
  types/index.ts
Labels: refactor

#26 fix: save and run data api params structure
  app/database/page.tsx
  components/DatabasePage/DBCard.tsx
  components/DatabasePage/FormDialog.tsx
  components/dbEditor.tsx
  public/icons/access.png
  public/icons/cassandra.png
  public/icons/couchbase.png
  public/icons/db2.png
  public/icons/hbase.png
  public/icons/postgresql.png
  public/icons/redis.png
  public/icons/sqlite.png
Labels: bug

#28 set fixed height for text input
  app/datastores/documents/page.tsx
  app/datastores/page.tsx
Labels: bug

#33 fix: dashboard miss run and save button
  client/api/tools/interceptors.ts
  components/chart/bar-chart.tsx
  components/chart/index.tsx
  components/chart/line-chart.tsx
  components/chart/table-chart.tsx
  components/chat/chat-container.tsx
  components/chat/chat-content.tsx
  components/chat/completion.tsx
  components/chat/db-editor.tsx
  components/chat/header/excel-upload.tsx
  components/chat/header/index.tsx
  components/chat/header/model-selector.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  styles/globals.css
Labels: bug, refactor

#34 feat: model management
  app/chat-context.tsx
  app/i18n.js
  client/api/request.ts
  client/api/tools/interceptors.ts
  components/chat/header/model-selector.tsx
  components/database/db-card.tsx
  components/database/db-icon.tsx
  components/database/form-dialog.tsx
  components/layout/left-side.tsx
  components/model/model-card.tsx
  components/model/model-form.tsx
  components/model/model-params.tsx
  pages/database/index.tsx
  pages/models/index.tsx
  public/icons/spark.png
  public/models/internlm.png
  styles/globals.css
  types/chart.ts
  types/db.ts
  types/model.ts
  utils/constants.ts
Labels: enhancement, refactor

#37 fix: form change follow model change
  components/model/model-form.tsx
  components/model/model-params.tsx
Labels: bug

#36 feat:support user feedback, promote management, etc.
  app/i18n.js
  client/api/request.ts
  components/chat/chat-container.tsx
  components/chat/chat-content.tsx
  components/chat/chat-feedback.tsx
  components/chat/completion.tsx
  components/common/prompt-bot.tsx
  components/layout/left-side.tsx
  components/prompt/prompt-modal.tsx
  package-lock.json
  package.json
  pages/index.tsx
  pages/prompt/index.tsx
  types/db.ts
Labels: feature
